//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public byte[] dp { get; set; }
        public string objectives { get; set; }
        public string academicDetails { get; set; }
        public string experience { get; set; }
        public string skills { get; set; }
        public string achievements { get; set; }
        public string otherInformation { get; set; }
        public string fullName { get; set; }
    }
}
