//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDT_FinalEntities : DbContext
    {
        public SDT_FinalEntities()
            : base("name=SDT_FinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<CV> CVs { get; set; }
        public virtual DbSet<junc_job_applicant> junc_job_applicant { get; set; }
        public virtual DbSet<company> companies { get; set; }
    }
}
