//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string skills { get; set; }
        public string city { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<bool> isOpen { get; set; }
    }
}
